### ISSUE TITLE
Exception - Array to string conversion

### ISSUE THREAD

**Issue by ArnauBlanch** [Sommerregen/grav-plugin-mediaembed#13]
Hello, after installing MediaEmbed, when I open the configuration page for the plugin I get this error:
>Server Error
Sorry, something went terribly wrong!
0 - An exception has been thrown during the rendering of a template ("Array to string conversion") in "forms/fields/toggle/toggle.html.twig" at line 46.
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

I hope you can fix this.
Thanks!

**Comment by fboes** [comment]
Same error, seen from `/logs/grav.log`:

```
[2016-01-11 13:39:30] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Array to string conversion") in "forms/fields/toggle/toggle.html.twig" at line 46. 

- Trace: 

#0 ~/grav/cache/twig/03/032….php(186): Twig_Template->displayBlock('input', Array, Array) 
#1 ~/grav/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_ca398bfa157b236a7e35c6e9c822b5081809bb3d0886c20650982e2addd2cf92->block_group(Array, Array) 
#2 ~/grav/cache/twig/03/032….php(130): Twig_Template->displayBlock('group', Array, Array) 
#3 ~/grav/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_ca398bfa157b236a7e35c6e9c822b5081809bb3d0886c20650982e2addd2cf92->block_contents(Array, Array) 
#4 ~/grav/cache/twig/03/032….php(57): Twig_Template->displayBlock('contents', Array, Array) 
#5 ~/grav/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_ca398bfa157b236a7e35c6e9c822b5081809bb3d0886c20650982e2addd2cf92->block_field(Array, Array) 
#6 ~/grav/cache/twig/03/032….php(44): Twig_Template->displayBlock('field', Array, Array) 
#7 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_ca398bfa157b236a7e35c6e9c822b5081809bb3d0886c20650982e2addd2cf92->doDisplay(Array, Array) 
#8 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#9 ~/grav/cache/twig/ca/ca7….php(45): Twig_Template->display(Array, Array) 
#10 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_f46ca206612aa0353e20f83dc622c692dfdbf530fb781eaa355d89c9ffe6fc8d->doDisplay(Array, Array) 
#11 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#12 ~/grav/cache/twig/3d/3d8….php(87): Twig_Template->display(Array) 
#13 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_61d82fc58c78a6e0a28fec8c5d8d9cc2b8896e559f0da02d7151a3667dbd8007->doDisplay(Array, Array) 
#14 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#15 ~/grav/cache/twig/3d/3d8….php(87): Twig_Template->display(Array) 
#16 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_61d82fc58c78a6e0a28fec8c5d8d9cc2b8896e559f0da02d7151a3667dbd8007->doDisplay(Array, Array) 
#17 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#18 ~/grav/cache/twig/08/083….php(84): Twig_Template->display(Array) 
#19 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_fecfa1453092b1d2b3bd7e13e4f43697bbecd3e5a2ee9d7c0b0cf62100743215->doDisplay(Array, Array) 
#20 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#21 ~/grav/cache/twig/03/03e….php(104): Twig_Template->display(Array) 
#22 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_0c6ac1a4eed2d65a2bb7c965ca06e42e4693f87962a54eb19b4abe7d1cae7cb1->doDisplay(Array, Array) 
#23 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#24 ~/grav/cache/twig/18/187….php(202): Twig_Template->display(Array) 
#25 ~/grav/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_94db7e0112f9b88958b9c1dd3ab8b7cd45ae1dfb82167dbe5c4184541f5c1b3e->block_content(Array, Array) 
#26 ~/grav/cache/twig/14/148….php(287): Twig_Template->displayBlock('content', Array, Array) 
#27 ~/grav/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_4d92c1517d8356461075b36a42dff8c9581a3bbfeff6820c613cdc57bfb8ced9->block_page(Array, Array) 
#28 ~/grav/cache/twig/14/148….php(45): Twig_Template->displayBlock('page', Array, Array) 
#29 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_4d92c1517d8356461075b36a42dff8c9581a3bbfeff6820c613cdc57bfb8ced9->doDisplay(Array, Array) 
#30 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#31 ~/grav/cache/twig/18/187….php(54): Twig_Template->display(Array, Array) 
#32 ~/grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_94db7e0112f9b88958b9c1dd3ab8b7cd45ae1dfb82167dbe5c4184541f5c1b3e->doDisplay(Array, Array) 
#33 ~/grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#34 ~/grav/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->display(Array) 
#35 ~/grav/vendor/twig/twig/lib/Twig/Environment.php(347): Twig_Template->render(Array) 
#36 ~/grav/system/src/Grav/Common/Twig/Twig.php(322): Twig_Environment->render('plugins.html.tw...', Array) 
#37 ~/grav/system/src/Grav/Common/Grav.php(157): Grav\Common\Twig\Twig->processSite(NULL) 
#38 ~/grav/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) 
#39 ~/grav/system/src/Grav/Common/Grav.php(257): Pimple\Container->offsetGet('output') 
#40 ~/grav/index.php(37): Grav\Common\Grav->process() 
#41 {main} [] []
```
